version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - flink_network
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - flink_network


  flink-jobmanager:
    image: flink:latest
    depends_on:
      - mysql
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    networks:
      - flink_network
    command: jobmanager

  flink-taskmanager:
    image: flink:latest
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    expose:
      - "6121"
      - "6122"
    ports:
      - "8082:8082"
    networks:
      - flink_network
    command: taskmanager

  mysql:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data
      - ./script/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      - flink_network

  fake-data-generator:
    image: chesterhsieh/streamming_lab
    depends_on:
      - kafka
    volumes:
      - ./fake_data_generator:/app
    command: python /app/generate_data.py
    networks:
      - flink_network
volumes:
  data:
networks:
  flink_network: